port: 9000
salt: abcdef
deploy: k8s
# 数据库配置
datasource:
  driverName: mysql
#  host: wz9q99i83cbphp2ngsl65.rwlb.rds.aliyuncs.com
  # 正式据库内网地址
  host: pc-wz9q99i83cbphp2ng.rwlb.rds.aliyuncs.com
  port: 3306
  database: ai-learning
  username: ai_learning
  password: ashA%jah#a3
  charset: utf8mb4
  loc: Asia/Shanghai

# grpc配置
grpc:
  localAddr: localhost:9001
  remoteAddr: localhost:9001
mongo:
  default:
    uri: mongodb://root:g9zkErI0DuHfrfOq@dds-wz9777a2c7b9dea41836-pub.mongodb.rds.aliyuncs.com:3717,dds-wz9777a2c7b9dea42131-pub.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-2414731
# 数仓接口配置
dataWarehouse:
  baseUrl: http://bigdata01.readboy.com:10073/easy-data-api/readboy_test
  appKey: 92097fa9cd7d4b88b47d979776010010
  appSecret: 2c1459ed8f3d430eb253d6c2d1f06510
# 中台接口配置
middleWare:
  #  baseUrl: https://middleground-test.readboy.com
  baseUrl: https://middleground.readboy.com
middleWare-test:
  baseUrl: https://middleground.readboy.com
# 吴宏煜作业系统接口配置
homeworkService:
  baseUrl: http://ai-learn-pad-svc:80
# 旧题库接口配置
questionBank:
  baseUrl: https://homework-api.readboy.com
# 新题库接口配置
dreamQuestionBank:
  baseUrl: http://dream-question-bank:8992
  appId: ailearning
  appSecret: 8bd6e8d42b8442cd930dbee5a6405ff46ce9aea5
# 验证token
verifyToken:
  baseUrl: http://login:80
# kafka 配置
kafka:
  brokers: alikafka-serverless-cn-bcd3st8pq01-1000-vpc.alikafka.aliyuncs.com:9092,alikafka-serverless-cn-bcd3st8pq01-2000-vpc.alikafka.aliyuncs.com:9092,alikafka-serverless-cn-bcd3st8pq01-3000-vpc.alikafka.aliyuncs.com:9092
  topic: ai-learn-wrong
  password: c3uTIX7cDlIGA0LMXhyfq65sxh5M9tCI
  user: alikafka_serverless-cn-bcd3st8pq01
#课程测试环境地址
courseUrl: http://dream-question-bank:8992
#题库url
topicUrl: http://dream-question-bank:8992
#学生推荐错题链接
wrongQuestionUrl: http://ai-learn-pad-svc:80

#学生账号生成
accountGenerator:
  baseUrl: https://api.ebag.readboy.com/stuaccountgenerator
  apiToken: ODRmNThkODFjZGMwNjExNzkxYzQzYmE2
# redis配置
redis:
  host: r-wz95d11ab6054724.redis.rds.aliyuncs.com:6379
  password: dreamTT1024
rabbitMq:
  host: rabbitmq-serverless-cn-lf63srd1e0f.cn-shenzhen.amqp-5.net.mq.amqp.aliyuncs.com
  userName: MjpyYWJiaXRtcS1zZXJ2ZXJsZXNzLWNuLWxmNjNzcmQxZTBmOkxUQUk1dFNYRmpEbmh5MUV3am1qVjk1cg==
  password: Qjg4OEZCOTdCRDY5Q0I5MjU3ODk3NjYzRjU5QTVFRkRCOTQyNUM0RjoxNzE5MjI4NjAwOTg4