port: 9001
salt: abcdef
deploy: local
# 数据库配置
datasource:
  driverName: mysql
  host: 172.16.1.205
  # 测试数据库内网地址
  #  host: rm-wz976878216hxs1yl.mysql.rds.aliyuncs.com
  port: 3306
  database: auto_article
  username: root
  password: 123
  charset: utf8mb4
  loc: Asia/Shanghai


#  driverName: mysql
#  host: wz9q99i83cbphp2ngsl65.rwlb.rds.aliyuncs.com
#  # 正式据库内网地址
#  #host: pc-wz9q99i83cbphp2ng.rwlb.rds.aliyuncs.com
#  port: 3306
#  database: ai-learning
#  username: ai_learning
#  password: ashA%jah#a3
#  charset: utf8mb4
#  loc: Asia/Shanghai

# kafka 配置
kafka:
  #  brokers: alikafka-serverless-cn-bcd3st8pq01-1000.alikafka.aliyuncs.com:9093,alikafka-serverless-cn-bcd3st8pq01-2000.alikafka.aliyuncs.com:9093,alikafka-serverless-cn-bcd3st8pq01-3000.alikafka.aliyuncs.com:9093
  #  topic: ai-learn-wrong-test
  #  password: c3uTIX7cDlIGA0LMXhyfq65sxh5M9tCI
  #  user: alikafka_serverless-cn-bcd3st8pq01
  brokers: 172.16.1.40:9192,172.16.1.40:9292,172.16.1.40:9392
  password: c3uTIX7cDlIGA0LMXhyfq65sxh5M9tCI
  user: alikafka_serverless-cn-bcd3st8pq01
# redis配置
redis:
  host: localhost:6379
  password: 123456
# 阿里云千问模型配置
aliYunModel:
  baseUrl: https://dashscope.aliyuncs.com/compatible-mode
  appKey: sk-f1aec03ebc8d416fab8e4122ea56fd39
rabbitMq:
  host: rabbitmq-serverless-cn-lf63srd1e0f.cn-shenzhen.amqp-5.net.mq.amqp.aliyuncs.com
  userName: MjpyYWJiaXRtcS1zZXJ2ZXJsZXNzLWNuLWxmNjNzcmQxZTBmOkxUQUk1dFNYRmpEbmh5MUV3am1qVjk1cg==
  password: Qjg4OEZCOTdCRDY5Q0I5MjU3ODk3NjYzRjU5QTVFRkRCOTQyNUM0RjoxNzE5MjI4NjAwOTg4
tianApiConfig:
    appKey: 2888c3780eeb28d089eff02089882e99
    baseUrl: https://apis.tianapi.com