CREATE TABLE IF NOT EXISTS `skill_generated_articles` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `task_id` varchar(64) NOT NULL DEFAULT '',
  `platform` varchar(32) NOT NULL DEFAULT '',
  `keyword` varchar(128) NOT NULL DEFAULT '',
  `keyword_segments` text,
  `category` varchar(64) NOT NULL DEFAULT '',
  `title` varchar(512) NOT NULL DEFAULT '',
  `title_options` text,
  `summary` text,
  `markdown_content` longtext,
  `html_preview` longtext,
  `tags` text,
  `cover_image_url` varchar(1024) NOT NULL DEFAULT '',
  `cover_image_type` varchar(32) NOT NULL DEFAULT '',
  `images` longtext,
  `sources` longtext,
  `hot_topics` longtext,
  `style_profile` text,
  `word_count` int NOT NULL DEFAULT 0,
  `model_provider` varchar(64) NOT NULL DEFAULT '',
  `model_name` varchar(128) NOT NULL DEFAULT '',
  `prompt_version` varchar(64) NOT NULL DEFAULT '',
  `skill_version` varchar(64) NOT NULL DEFAULT '',
  `humanize_status` varchar(32) NOT NULL DEFAULT 'pending',
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `publish_status` varchar(32) NOT NULL DEFAULT 'unpublished',
  `publish_payload` longtext,
  `error_message` text,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_skill_generated_articles_task_id` (`task_id`),
  KEY `idx_skill_generated_articles_platform` (`platform`),
  KEY `idx_skill_generated_articles_keyword` (`keyword`),
  KEY `idx_skill_generated_articles_category` (`category`),
  KEY `idx_skill_generated_articles_status` (`status`),
  KEY `idx_skill_generated_articles_publish_status` (`publish_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
